; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=전기실SCADA
AppVersion=1.0
DefaultDirName={autopf}\ElecRoomSCADA
DefaultGroupName=전기실SCADA
OutputBaseFilename=전기실SCADA_Setup
Compression=lzma
SolidCompression=yes

[Files]
; 1. 먼저 _internal 폴더의 모든 내용을 복사합니다.
Source: "E:\elecroomscada_mariadb\dist\main\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs

; 2. main.exe를 복사합니다.
Source: "E:\elecroomscada_mariadb\dist\main\main.exe"; DestDir: "{app}"; Flags: ignoreversion

; 3. 템플릿 파일만 별도로 지정하여 설치 폴더 루트({app})에 복사합니다.
Source: "E:\elecroomscada_mariadb\dist\main\_internal\template_전기실_운영일지.xlsx"; DestDir: "{app}"; Flags: ignoreversion

; 4. 아이콘 파일 (나중에 바로가기 생성 시 경로를 참조하기 위함)
Source: "free-icon-folder-2015058.ico"; DestDir: "{app}"

; 5. config.ini 파일만 별도로 지정하여 설치 폴더 루트({app})에 복사합니다.
Source: "E:\elecroomscada_mariadb\dist\main\_internal\config.ini"; DestDir: "{app}"; Flags: ignoreversion
;"D:\elecroomscada_mariadb\dist\main\_internal\config.ini"

[Icons]
; 바탕화면에 아이콘 생성
Name: "{autodesktop}\전기실SCADA"; Filename: "{app}\main.exe"; IconFilename: "{app}\free-icon-folder-2015058.ico"; WorkingDir: "{app}"
; 시작 메뉴에 바로가기 생성
Name: "{group}\전기실SCADA"; Filename: "{app}\main.exe"; IconFilename: "{app}\free-icon-folder-2015058.ico"

[Run]
; 설치 완료 후 바로 실행
Filename: "{app}\main.exe"; Description: "프로그램 실행"; Flags: nowait postinstall skipifsilent