; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=전기실SCADA
AppVersion=1.0
DefaultDirName={autopf}\ElecRoomSCADA
DefaultGroupName=전기실SCADA
OutputBaseFilename=전기실SCADA_Setup
Compression=lzma
SolidCompression=yes

[Files]
; 어제 빌드한 dist/main 폴더 안의 모든 파일을 지정합니다.
; Source 뒤에 경로를 어제 빌드했던 dist\main 폴더로 적어주세요.
Source: "D:\mariadbelecroomscada\dist\main\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; 바탕화면에 아이콘 생성
Name: "{autodesktop}\전기실SCADA"; Filename: "{app}\main.exe"; WorkingDir: "{app}"
; 시작 메뉴에 바로가기 생성
Name: "{group}\전기실SCADA"; Filename: "{app}\main.exe"

[Run]
; 설치 완료 후 바로 실행
Filename: "{app}\main.exe"; Description: "프로그램 실행"; Flags: nowait postinstall skipifsilent